manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name:
      url-base: https://github.com/nickconway/zmk.git
  projects:
    - name: zmk
      remote: nickconway
      revision: smart-interrupt
      import: app/west.yml
  self:
    path: config
